### ISSUE TITLE
ImportError: cannot import name 'PeftSavingCallback' from 'trl.trainer.utils'

### ISSUE THREAD

**Issue by Godlikemandyy** [ktlKTL/C-LLM#1]
<img width="1192" alt="image" src="https://github.com/ktlKTL/C-LLM/assets/36065226/e9c14793-d449-4c62-a45f-c4978ad33c13">

Try running train.sh, how to solve the above error, thank you！

**Comment by ktlKTL** [comment]
hi~, I don't have this error in my environment, maybe you can try installing trl==0.7.4.

**Comment by Godlikemandyy** [comment]
> hi~, I don't have this error in my environment, maybe you can try installing trl==0.7.4.

我尝试把trl换成了0.7.4，但是又报下面的错误：
<img width="1187" alt="image" src="https://github.com/ktlKTL/C-LLM/assets/36065226/201ab80d-055c-4ad0-88bd-b30c139883c2">

**Comment by ktlKTL** [comment]
hi, 我觉得是transformers版本问题，在我的环境下transformers==4.37.2, trl==0.7.4是可以跑的

**Comment by Godlikemandyy** [comment]
> hi, 我觉得是transformers版本问题，在我的环境下transformers==4.37.2, trl==0.7.4是可以跑的

transformer和trl都按你说的版本替换了：
<img width="331" alt="image" src="https://github.com/ktlKTL/C-LLM/assets/36065226/e0671a64-4415-4f79-9427-d84e0a769aa4">
但还是报下面的错误：
<img width="1189" alt="image" src="https://github.com/ktlKTL/C-LLM/assets/36065226/cba5103e-6642-49f0-947c-50c409b3424b">

**Comment by ktlKTL** [comment]
嗯嗯好的，
1）第一个报错我觉得可能是torch没有安装gpu版本的问题，可以按照你的cuda安装torch，比如：
pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118

2）然后对于第二个报错，deepspeed参数文件已更新在repo中，可以下载到文件夹里运行～（注意修改路径

(另外requirement.txt也已更新，感谢关注

**Comment by Godlikemandyy** [comment]
> 嗯嗯好的， 1）第一个报错我觉得可能是torch没有安装gpu版本的问题，可以按照你的cuda安装torch，比如： pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118
> 
> 2）然后对于第二个报错，deepspeed参数文件已更新在repo中，可以下载到文件夹里运行～（注意修改路径
> 
> (另外requirement.txt也已更新，感谢关注

第二个错误没有了，但是第一个错误还是存在，我使用了下面的命令安装了torch：
pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121
但是报错信息如下：
<img width="1191" alt="image" src="https://github.com/ktlKTL/C-LLM/assets/36065226/0589c05f-1caa-4b56-8755-0ef70ddb7a49">
显卡信息如下：
<img width="695" alt="image" src="https://github.com/ktlKTL/C-LLM/assets/36065226/2db2c92e-6e86-4ac6-88de-d2a17a8d5def">
还有就是你更新的requirements.txt里面的xformers==0.0.21，安装的时候会自动下载torch2.0.1的，跟里面的2.1.2冲突啊

**Comment by ktlKTL** [comment]
喔喔这样，请确保accelerate库是否安装了？如果还是有报错的话，可以参考https://blog.csdn.net/HaoZiHuang/article/details/123645660 打印出详细错误再看一下

另外xformers影响不是很大，改成xformers==0.0.23.post1也是可以的～

**Comment by Godlikemandyy** [comment]
> 喔喔这样，请确保accelerate库是否安装了？如果还是有报错的话，可以参考https://blog.csdn.net/HaoZiHuang/article/details/123645660 打印出详细错误再看一下
> 
> 另外xformers影响不是很大，改成xformers==0.0.23.post1也是可以的～

方便加微信交流吗

**Comment by ktlKTL** [comment]
更新：单卡环境下，可以修改train.sh 中的 --nproc_per_node=1
