### ISSUE TITLE
 more details about the Continued Pre-training step

### ISSUE THREAD

**Issue by Jackson-agent** [ktlKTL/C-LLM#2]
I found your work very interesting. Could you please provide more details about the Continued Pre-training step? Specifically, I'm curious about how the model is pretrained during this phase.

**Comment by ktlKTL** [comment]
Hello, thank you for your attention to our work!

The continued pre-training is conducted by performing next token prediction on 2B tokens. The training data comes from the Chinese pre-training corpus in TigerBot: https://huggingface.co/datasets/TigerResearch/pretrain_zh. 

For more details, you can refer to our paper (https://arxiv.org/pdf/2406.16536). We will also be releasing the parameters of the model soon, so please stay tuned ～
