### ISSUE TITLE
SMBERT Baseline

### ISSUE THREAD

**Issue by JieWu02** [ktlKTL/C-LLM#3]
Congratulations on your fantastic work! I am reaching out to kindly ask if you would be willing to share the training scripts for SMBERT. Is it necessary to extract labels manually when training SMBERT on a new dataset?

Thank you for your time and consideration, and I look forward to your response.

Wishing you continued success in your research!

**Comment by ktlKTL** [comment]
Hello! thank you very much for your attention and recognition of our work. 

We primarily follow this repo to train SMBERT:https://github.com/gitabtion/BertBasedCorrectionModels. Additionally, when training SMBERT on a new dataset, it is indeed necessary to extract the labels first ~

**Comment by JieWu02** [comment]
> Hello! thank you very much for your attention and recognition of our work.
> 
> We primarily follow this repo to train SMBERT:https://github.com/gitabtion/BertBasedCorrectionModels. Additionally, when training SMBERT on a new dataset, it is indeed necessary to extract the labels first ~

Thank you~~
